seed: 32
fe: 0
proj: 1
num_workers: 4
aug: "dnodes"
epoch: 50
batch: 2048
lr: 0.0001
num_gc_layers: 4
head_layers: 1
hidden_dim: 128
residual: 0
JK: "sum"
pool: "mean"
num_latent_factors: 3
tau: 0.2
drop_ratio: 0.3
log_dir: "log"
