seed: 32
fe: 1
proj: 1
num_workers: 8
aug: "random4"
epoch: 10
batch: 512
lr: 0.001
num_gc_layers: 2
head_layers: 1
hidden_dim: 512
residual: 0
JK: "last"
pool: "max"
num_latent_factors: 5
tau: 0.2
drop_ratio: 0.3
log_dir: "log"