seed: 32
fe: 0
proj: 1
num_workers: 8
aug: "random4"
epoch: 20
batch: 256
lr: 0.0001
num_gc_layers: 3
head_layers: 1
hidden_dim: 512
residual: 0
JK: "sum"
pool: "max"
num_latent_factors: 5
tau: 0.2
drop_ratio: 0.5
log_dir: "log"