search: True
# seed: 42
# fe: 0
# proj: 1
num_workers: 8
aug: "dnodes"
epochs: 50
batch_size: 512
lr: 0.001
n_layers: 4
head_layers: 1
h_dim: 128
two_aug: False
# residual: 0
# JK: "sum"
# pool: "mean"
# num_latent_factors: 3
weight_decay: 0.0001
tau: 0.2
drop_ratio: 0.3
intraview_negs: True
# log_dir: "log"
use_scheduler: True
log_interval: 2